name: Cypress CICD Integration Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 22 * * *"  # Ejecuta diariamente a las 22:00 UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  cypress-smoke:
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress smoke tests
      run: npm run cy:smoke
      env:
        CI: true

  cypress-regression:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress regression tests
      run: npm run cy:regression
      env:
        CI: true

  cypress-better-login:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress better login tests
      run: npm run cy:betterLogin
      env:
        CI: true

  cypress-login-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress login test
      run: npm run cy:loginTest
      env:
        CI: true

  cypress-main-page:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress main page tests
      run: npm run cy:mainPage
      env:
        CI: true

